version: "3.3"
# start with docker compose up --build

services:
  backend:
    build: .
    ports:
    - "3000:3000"
    networks:
    - one-place-network
    environment:
      DATABASE_URL: file:/app/prisma/dev.db # prepopulated db is provided in prisma/dev.db, change filename for fresh instance

networks:
  one-place-network: