name: Build Android executable 

on:
  push:
  workflow_dispatch:
    inputs:
      api_url:
        description: "Backend URL"
        required: true

jobs:
  build:
    runs-on: ubuntu-latest
    env:
      EXPO_PUBLIC_API_URL: "http://${{ secrets.EXPO_PUBLIC_API_URL }}:3000"
    steps:
      - name: Checkout code
        run: actions/checkout@v5
        branch-depth: 0
        working-directory: frontend

      - name: Install dependencies
        run: cd frontend && npm install
        working-directory: frontend

      - name: Generate android/ folder
        run: npx expo prebuild --platform android
        working-directory: frontend

      - name: Set up JDK 17
        uses: actions/setup-java@v4
        working-directory: frontend/android
        with:
          distribution: temurin
          java-version: 17
          cache: gradle

      - name: Set up Android SDK
        uses: android-actions/setup-android@v3
        working-directory: frontend/android

      - name: Accept SDK licenses
        run: yes | sdkmanager --licenses
        working-directory: frontend/android

      - name: Build Debug APK
        run: ./gradlew assembleDebug
        working-directory: frontend/android

      - name: Upload APK
        uses: actions/upload-artifact@v4
        working-directory: frontend/android
        with:
          name: app-debug
          path: app/build/outputs/apk/debug/*.apk

  # test:
  #   runs-on: ubuntu-latest
  #   steps:    
  #     - name: Checkout code
  #       run: actions/checkout@v5
  #       depth: 0

  #     - name: Install dependencies
  #       run: cd frontend && npm install

  #     - name: Run tests
  #       run: cd frontend && npm run test
